# Generated by Django 4.1.1 on 2022-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('pic_url', models.CharField(default='', max_length=1024)),
                ('news_url', models.CharField(default='', max_length=1024)),
                ('submit_by', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=64)),
                ('notes', models.TextField()),
            ],
        ),
    ]
